version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-flask-helloworld
    volumes:
      - ".:/app"
    env_file:
      - .env.dev
    ports:
      - "5001:5000"
    tty: true
