version: "3.9"

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-flask-helloworld
    env_file:
      - .env
    ports:
      - "5001:5000"
    tty: true