apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-02-05T22:39:59Z"
  generation: 1
  labels:
    app: python-flask-helloworld
  name: python-flask-helloworld
  namespace: default
  resourceVersion: "3933"
  uid: 62a63167-2654-4095-8ed2-2de9f4f2ccff
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python-flask-helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-flask-helloworld
    spec:
      containers:
      - image: caprilespe/python-flask-helloworld:v1
        imagePullPolicy: IfNotPresent
        name: python-flask-helloworld
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-05T22:40:07Z"
    lastUpdateTime: "2023-02-05T22:40:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-02-05T22:39:59Z"
    lastUpdateTime: "2023-02-05T22:40:07Z"
    message: ReplicaSet "python-flask-helloworld-54db6f4565" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
