apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-05T22:46:10Z"
  labels:
    app: python-flask-helloworld
  name: python-flask-helloworld
  namespace: default
  resourceVersion: "4199"
  uid: 7a3124d6-7cee-4c0b-ba71-741764ffb6cb
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.58.213
  clusterIPs:
  - 10.104.58.213
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32072
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-flask-helloworld
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
